### ISSUE TITLE
Deployed URL is broken

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-fiber#11]
Something isn't working with the github pages, it hangs on "waiting for renderer"

https://tscircuit.github.io/jscad-fiber/

![image](https://github.com/tscircuit/jscad-fiber/assets/1910070/f022278a-11f9-445e-897b-0e99b1850707)

**Comment by ovidiuch** [comment]
Please see https://github.com/react-cosmos/react-cosmos/issues/925

**Comment by seveibar** [comment]
@ovidiuch that fixed it thank you!!!!
