### ISSUE TITLE
Add `rotation` as a prop to `<Rotate />` (alias of `angles`)

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-fiber#38]
instead of `angles` we should accept `rotation`, going to create an issue to add that as an accepted prop (we can accept both)

_Originally posted by @seveibar in https://github.com/tscircuit/jscad-fiber/issues/37#issuecomment-2246277540_

**Comment by Slaviiiii** [comment]
You want me to replace angles with rotation?
I think jscad requires it to be called that way.

**Comment by seveibar** [comment]
@Slaviiiii it's just an alias, so we accept either then give jscad the one it requires. `<Translate />` does this too by accepting either `center` or `offset`

**Comment by Slaviiiii** [comment]
@seveibar I see what you mean with this.
Get the required ``rotation`` prop and then make ``angles={rotation}``.
