### ISSUE TITLE
Show code examples on usage site

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-fiber#89]
Currently we build to a usage site here: https://tscircuit.github.io/jscad-fiber

But there is no way to see the code for each example. Let's create a way to see the code for each example. This will help people learn to use jscad-fiber better.

/bounty $40

**Comment by DhairyaMajmudar** [comment]
@seveibar How's about adding a code button here in the side menu 

![Image](https://github.com/user-attachments/assets/e124026f-e6d7-4f77-a4d1-34e50a076763)

and then rendering code snippets below side panel ? 

![Image](https://github.com/user-attachments/assets/30b9f948-7719-44ff-8ffe-f9ecf7a8cf51)



Would like to get your inputs here and assigned the issue to me : )

**Comment by anas-sarkez** [comment]
@DhairyaMajmudar go ahead with that

**Comment by DevGajjar28** [comment]
hey @seveibar I had a try and make this ![Image](https://github.com/user-attachments/assets/be59d0c8-d1fb-4dc9-91ad-9d1977600397)

**Comment by DevGajjar28** [comment]
> hey [@seveibar](https://github.com/seveibar) I had a try and make this ![Image](https://github.com/user-attachments/assets/be59d0c8-d1fb-4dc9-91ad-9d1977600397)

To be honest, I’ve been working on it since yesterday. I haven’t commented yet because I wasn’t sure, but I gave it a try and finally got it done!

**Comment by seveibar** [comment]
@anas-sarkez can you post your screenshot? It was pretty good- i think it was definitely an acceptable aesthetic

**Comment by seveibar** [comment]
@DevGajjar28 looks ok but yea syntax highlighting and more of an overlay or integrated into cosmos is better.

As far as who gets it im just going to merge PRs and do reviews like i normally would, for frequent contributors i do assignments but this repo doesnt have many freqent contributors

**Comment by anas-sarkez** [comment]
![Image](https://github.com/user-attachments/assets/de705e8f-b0e3-4d9e-a898-1035ce945512)

**Comment by DevGajjar28** [comment]
Hey @seveibar, I have completed the task and am raising my PR. Please review it! 
Preview:
https://github.com/user-attachments/assets/882150b1-15ef-498f-aaee-0d76af81c935
